/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AggregateIndicators {
    #[serde(rename = "technicalAnalysis", skip_serializing_if = "Option::is_none")]
    pub technical_analysis: Option<Box<models::TechnicalAnalysis>>,
    #[serde(rename = "trend", skip_serializing_if = "Option::is_none")]
    pub trend: Option<Box<models::Trend>>,
}

impl AggregateIndicators {
    pub fn new() -> AggregateIndicators {
        AggregateIndicators {
            technical_analysis: None,
            trend: None,
        }
    }
}
