/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatResponse {
    /// Chat ID.
    #[serde(rename = "chatId", skip_serializing_if = "Option::is_none")]
    pub chat_id: Option<String>,
    /// Response text.
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Query summary
    #[serde(rename = "querySummary", skip_serializing_if = "Option::is_none")]
    pub query_summary: Option<String>,
    /// Related queries.
    #[serde(rename = "relatedQueries", skip_serializing_if = "Option::is_none")]
    pub related_queries: Option<Vec<serde_json::Value>>,
    /// List of tickers mentioned.
    #[serde(rename = "tickers", skip_serializing_if = "Option::is_none")]
    pub tickers: Option<Vec<serde_json::Value>>,
    /// Sources.
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<Vec<serde_json::Value>>,
    /// Widgets.
    #[serde(rename = "widgets", skip_serializing_if = "Option::is_none")]
    pub widgets: Option<Vec<serde_json::Value>>,
}

impl AiChatResponse {
    pub fn new() -> AiChatResponse {
        AiChatResponse {
            chat_id: None,
            content: None,
            query_summary: None,
            related_queries: None,
            tickers: None,
            sources: None,
            widgets: None,
        }
    }
}
