/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AiChatBody {
    /// Messages
    #[serde(rename = "messages")]
    pub messages: Vec<models::AiChatMessage>,
    /// Stream responses
    #[serde(rename = "stream", skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,
}

impl AiChatBody {
    pub fn new(messages: Vec<models::AiChatMessage>) -> AiChatBody {
        AiChatBody {
            messages,
            stream: None,
        }
    }
}
