/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AirlinePriceIndex {
    /// Date
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// Price Index
    #[serde(rename = "priceIndex", skip_serializing_if = "Option::is_none")]
    pub price_index: Option<f32>,
    /// Daily average ticket price.
    #[serde(rename = "dailyAvgPrice", skip_serializing_if = "Option::is_none")]
    pub daily_avg_price: Option<f32>,
}

impl AirlinePriceIndex {
    pub fn new() -> AirlinePriceIndex {
        AirlinePriceIndex {
            date: None,
            price_index: None,
            daily_avg_price: None,
        }
    }
}
