/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AirlinePriceIndexData {
    /// Array of price index.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::AirlinePriceIndex>>,
    /// Airline name
    #[serde(rename = "airline", skip_serializing_if = "Option::is_none")]
    pub airline: Option<String>,
    /// From date
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    /// To date
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
}

impl AirlinePriceIndexData {
    pub fn new() -> AirlinePriceIndexData {
        AirlinePriceIndexData {
            data: None,
            airline: None,
            from: None,
            to: None,
        }
    }
}
