/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BasicFinancials {
    /// Symbol of the company.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Metric type.
    #[serde(rename = "metricType", skip_serializing_if = "Option::is_none")]
    pub metric_type: Option<String>,
    #[serde(rename = "series", skip_serializing_if = "Option::is_none")]
    pub series: Option<serde_json::Value>,
    #[serde(rename = "metric", skip_serializing_if = "Option::is_none")]
    pub metric: Option<serde_json::Value>,
}

impl BasicFinancials {
    pub fn new() -> BasicFinancials {
        BasicFinancials {
            symbol: None,
            metric_type: None,
            series: None,
            metric: None,
        }
    }
}
