/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BondTickData {
    /// Number of ticks skipped.
    #[serde(rename = "skip", skip_serializing_if = "Option::is_none")]
    pub skip: Option<i64>,
    /// Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Total number of ticks for that date.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
    /// List of volume data.
    #[serde(rename = "v", skip_serializing_if = "Option::is_none")]
    pub v: Option<Vec<f32>>,
    /// List of price data.
    #[serde(rename = "p", skip_serializing_if = "Option::is_none")]
    pub p: Option<Vec<f32>>,
    /// List of yield data.
    #[serde(rename = "y", skip_serializing_if = "Option::is_none")]
    pub y: Option<Vec<f32>>,
    /// List of timestamp in UNIX ms.
    #[serde(rename = "t", skip_serializing_if = "Option::is_none")]
    pub t: Option<Vec<i64>>,
    /// List of values showing the side (Buy/sell) of each trade. List of supported values: <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing\",>here</a>
    #[serde(rename = "si", skip_serializing_if = "Option::is_none")]
    pub si: Option<Vec<String>>,
    /// List of values showing the counterparty of each trade. List of supported values: <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing\",>here</a>
    #[serde(rename = "cp", skip_serializing_if = "Option::is_none")]
    pub cp: Option<Vec<String>>,
    /// List of values showing the reporting party of each trade. List of supported values: <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing\",>here</a>
    #[serde(rename = "rp", skip_serializing_if = "Option::is_none")]
    pub rp: Option<Vec<String>>,
    /// ATS flag. Y or empty
    #[serde(rename = "ats", skip_serializing_if = "Option::is_none")]
    pub ats: Option<Vec<String>>,
    /// List of trade conditions. A comprehensive list of trade conditions code can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1O3aueXSPOqo7Iuyz4PqDG6yZunHsX8BTefZ2kFk5pz4/edit?usp=sharing\">here</a>
    #[serde(rename = "c", skip_serializing_if = "Option::is_none")]
    pub c: Option<Vec<Vec<String>>>,
}

impl BondTickData {
    pub fn new() -> BondTickData {
        BondTickData {
            skip: None,
            count: None,
            total: None,
            v: None,
            p: None,
            y: None,
            t: None,
            si: None,
            cp: None,
            rp: None,
            ats: None,
            c: None,
        }
    }
}
