/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BondProfile {
    /// ISIN.
    #[serde(rename = "isin", skip_serializing_if = "Option::is_none")]
    pub isin: Option<String>,
    /// Cusip.
    #[serde(rename = "cusip", skip_serializing_if = "Option::is_none")]
    pub cusip: Option<String>,
    /// FIGI.
    #[serde(rename = "figi", skip_serializing_if = "Option::is_none")]
    pub figi: Option<String>,
    /// Coupon.
    #[serde(rename = "coupon", skip_serializing_if = "Option::is_none")]
    pub coupon: Option<f32>,
    /// Period.
    #[serde(rename = "maturityDate", skip_serializing_if = "Option::is_none")]
    pub maturity_date: Option<String>,
    /// Offering price.
    #[serde(rename = "offeringPrice", skip_serializing_if = "Option::is_none")]
    pub offering_price: Option<f32>,
    /// Issue date.
    #[serde(rename = "issueDate", skip_serializing_if = "Option::is_none")]
    pub issue_date: Option<String>,
    /// Bond type.
    #[serde(rename = "bondType", skip_serializing_if = "Option::is_none")]
    pub bond_type: Option<String>,
    /// Bond type.
    #[serde(rename = "debtType", skip_serializing_if = "Option::is_none")]
    pub debt_type: Option<String>,
    /// Industry.
    #[serde(rename = "industryGroup", skip_serializing_if = "Option::is_none")]
    pub industry_group: Option<String>,
    /// Sub-Industry.
    #[serde(rename = "industrySubGroup", skip_serializing_if = "Option::is_none")]
    pub industry_sub_group: Option<String>,
    /// Asset.
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    /// Asset.
    #[serde(rename = "assetType", skip_serializing_if = "Option::is_none")]
    pub asset_type: Option<String>,
    /// Dated date.
    #[serde(rename = "datedDate", skip_serializing_if = "Option::is_none")]
    pub dated_date: Option<String>,
    /// First coupon date.
    #[serde(rename = "firstCouponDate", skip_serializing_if = "Option::is_none")]
    pub first_coupon_date: Option<String>,
    /// Offering amount.
    #[serde(rename = "originalOffering", skip_serializing_if = "Option::is_none")]
    pub original_offering: Option<f32>,
    /// Outstanding amount.
    #[serde(rename = "amountOutstanding", skip_serializing_if = "Option::is_none")]
    pub amount_outstanding: Option<f32>,
    /// Payment frequency.
    #[serde(rename = "paymentFrequency", skip_serializing_if = "Option::is_none")]
    pub payment_frequency: Option<String>,
    /// Security level.
    #[serde(rename = "securityLevel", skip_serializing_if = "Option::is_none")]
    pub security_level: Option<String>,
    /// Callable.
    #[serde(rename = "callable", skip_serializing_if = "Option::is_none")]
    pub callable: Option<bool>,
    /// Coupon type.
    #[serde(rename = "couponType", skip_serializing_if = "Option::is_none")]
    pub coupon_type: Option<String>,
}

impl BondProfile {
    pub fn new() -> BondProfile {
        BondProfile {
            isin: None,
            cusip: None,
            figi: None,
            coupon: None,
            maturity_date: None,
            offering_price: None,
            issue_date: None,
            bond_type: None,
            debt_type: None,
            industry_group: None,
            industry_sub_group: None,
            asset: None,
            asset_type: None,
            dated_date: None,
            first_coupon_date: None,
            original_offering: None,
            amount_outstanding: None,
            payment_frequency: None,
            security_level: None,
            callable: None,
            coupon_type: None,
        }
    }
}
