/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BondYieldCurveInfo {
    /// Date of the reading
    #[serde(rename = "d", skip_serializing_if = "Option::is_none")]
    pub d: Option<String>,
    /// Value
    #[serde(rename = "v", skip_serializing_if = "Option::is_none")]
    pub v: Option<f32>,
}

impl BondYieldCurveInfo {
    pub fn new() -> BondYieldCurveInfo {
        BondYieldCurveInfo { d: None, v: None }
    }
}
