/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BondCandles {
    /// List of close prices for returned candles.
    #[serde(rename = "c", skip_serializing_if = "Option::is_none")]
    pub c: Option<Vec<f32>>,
    /// List of timestamp for returned candles.
    #[serde(rename = "t", skip_serializing_if = "Option::is_none")]
    pub t: Option<Vec<i64>>,
    /// Status of the response. This field can either be ok or no_data.
    #[serde(rename = "s", skip_serializing_if = "Option::is_none")]
    pub s: Option<String>,
}

impl BondCandles {
    pub fn new() -> BondCandles {
        BondCandles {
            c: None,
            t: None,
            s: None,
        }
    }
}
