/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BreakdownItem {
    /// Access number of the report from which the data is sourced.
    #[serde(rename = "accessNumber", skip_serializing_if = "Option::is_none")]
    pub access_number: Option<String>,
    #[serde(rename = "breakdown", skip_serializing_if = "Option::is_none")]
    pub breakdown: Option<serde_json::Value>,
}

impl BreakdownItem {
    pub fn new() -> BreakdownItem {
        BreakdownItem {
            access_number: None,
            breakdown: None,
        }
    }
}
