/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompanyNewsStatistics {
    ///
    #[serde(rename = "articlesInLastWeek", skip_serializing_if = "Option::is_none")]
    pub articles_in_last_week: Option<i64>,
    ///
    #[serde(rename = "buzz", skip_serializing_if = "Option::is_none")]
    pub buzz: Option<f32>,
    ///
    #[serde(rename = "weeklyAverage", skip_serializing_if = "Option::is_none")]
    pub weekly_average: Option<f32>,
}

impl CompanyNewsStatistics {
    pub fn new() -> CompanyNewsStatistics {
        CompanyNewsStatistics {
            articles_in_last_week: None,
            buzz: None,
            weekly_average: None,
        }
    }
}
