/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompanyExecutive {
    /// Company symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Array of company's executives and members of the Board.
    #[serde(rename = "executive", skip_serializing_if = "Option::is_none")]
    pub executive: Option<Vec<models::Company>>,
}

impl CompanyExecutive {
    pub fn new() -> CompanyExecutive {
        CompanyExecutive {
            symbol: None,
            executive: None,
        }
    }
}
