/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompanyProfile2 {
    /// Country of company's headquarter.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Currency used in company filings.
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// Listed exchange.
    #[serde(rename = "exchange", skip_serializing_if = "Option::is_none")]
    pub exchange: Option<String>,
    /// Company name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Company symbol/ticker as used on the listed exchange.
    #[serde(rename = "ticker", skip_serializing_if = "Option::is_none")]
    pub ticker: Option<String>,
    /// IPO date.
    #[serde(rename = "ipo", skip_serializing_if = "Option::is_none")]
    pub ipo: Option<String>,
    /// Market Capitalization.
    #[serde(
        rename = "marketCapitalization",
        skip_serializing_if = "Option::is_none"
    )]
    pub market_capitalization: Option<f32>,
    /// Number of oustanding shares.
    #[serde(rename = "shareOutstanding", skip_serializing_if = "Option::is_none")]
    pub share_outstanding: Option<f32>,
    /// Logo image.
    #[serde(rename = "logo", skip_serializing_if = "Option::is_none")]
    pub logo: Option<String>,
    /// Company phone number.
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
    /// Company website.
    #[serde(rename = "weburl", skip_serializing_if = "Option::is_none")]
    pub weburl: Option<String>,
    /// Finnhub industry classification.
    #[serde(rename = "finnhubIndustry", skip_serializing_if = "Option::is_none")]
    pub finnhub_industry: Option<String>,
}

impl CompanyProfile2 {
    pub fn new() -> CompanyProfile2 {
        CompanyProfile2 {
            country: None,
            currency: None,
            exchange: None,
            name: None,
            ticker: None,
            ipo: None,
            market_capitalization: None,
            share_outstanding: None,
            logo: None,
            phone: None,
            weburl: None,
            finnhub_industry: None,
        }
    }
}
