/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CongressionalTransaction {
    /// Transaction amount from.
    #[serde(rename = "amountFrom", skip_serializing_if = "Option::is_none")]
    pub amount_from: Option<f32>,
    /// Transaction amount to.
    #[serde(rename = "amountTo", skip_serializing_if = "Option::is_none")]
    pub amount_to: Option<f32>,
    /// Asset name.
    #[serde(rename = "assetName", skip_serializing_if = "Option::is_none")]
    pub asset_name: Option<String>,
    /// Filing date.
    #[serde(rename = "filingDate", skip_serializing_if = "Option::is_none")]
    pub filing_date: Option<String>,
    /// Name of the representative.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Owner Type.
    #[serde(rename = "ownerType", skip_serializing_if = "Option::is_none")]
    pub owner_type: Option<String>,
    /// Position.
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<String>,
    /// Symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Transaction date.
    #[serde(rename = "transactionDate", skip_serializing_if = "Option::is_none")]
    pub transaction_date: Option<String>,
    /// Transaction type <code>Sale</code> or <code>Purchase</code>.
    #[serde(rename = "transactionType", skip_serializing_if = "Option::is_none")]
    pub transaction_type: Option<String>,
}

impl CongressionalTransaction {
    pub fn new() -> CongressionalTransaction {
        CongressionalTransaction {
            amount_from: None,
            amount_to: None,
            asset_name: None,
            filing_date: None,
            name: None,
            owner_type: None,
            position: None,
            symbol: None,
            transaction_date: None,
            transaction_type: None,
        }
    }
}
