/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CountryMetadata {
    /// Country name
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Alpha 2 code
    #[serde(rename = "code2", skip_serializing_if = "Option::is_none")]
    pub code2: Option<String>,
    /// Alpha 3 code
    #[serde(rename = "code3", skip_serializing_if = "Option::is_none")]
    pub code3: Option<String>,
    /// UN code
    #[serde(rename = "codeNo", skip_serializing_if = "Option::is_none")]
    pub code_no: Option<String>,
    /// Currency name
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// Currency code
    #[serde(rename = "currencyCode", skip_serializing_if = "Option::is_none")]
    pub currency_code: Option<String>,
    /// Region
    #[serde(rename = "region", skip_serializing_if = "Option::is_none")]
    pub region: Option<String>,
    /// Sub-Region
    #[serde(rename = "subRegion", skip_serializing_if = "Option::is_none")]
    pub sub_region: Option<String>,
    /// Moody's credit risk rating.
    #[serde(rename = "rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<String>,
    /// Default spread
    #[serde(rename = "defaultSpread", skip_serializing_if = "Option::is_none")]
    pub default_spread: Option<f32>,
    /// Country risk premium
    #[serde(rename = "countryRiskPremium", skip_serializing_if = "Option::is_none")]
    pub country_risk_premium: Option<f32>,
    /// Equity risk premium
    #[serde(rename = "equityRiskPremium", skip_serializing_if = "Option::is_none")]
    pub equity_risk_premium: Option<f32>,
}

impl CountryMetadata {
    pub fn new() -> CountryMetadata {
        CountryMetadata {
            country: None,
            code2: None,
            code3: None,
            code_no: None,
            currency: None,
            currency_code: None,
            region: None,
            sub_region: None,
            rating: None,
            default_spread: None,
            country_risk_premium: None,
            equity_risk_premium: None,
        }
    }
}
