/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CovidInfo {
    /// State.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<String>,
    /// Number of confirmed cases.
    #[serde(rename = "case", skip_serializing_if = "Option::is_none")]
    pub case: Option<f32>,
    /// Number of confirmed deaths.
    #[serde(rename = "death", skip_serializing_if = "Option::is_none")]
    pub death: Option<f32>,
    /// Updated time.
    #[serde(rename = "updated", skip_serializing_if = "Option::is_none")]
    pub updated: Option<String>,
}

impl CovidInfo {
    pub fn new() -> CovidInfo {
        CovidInfo {
            state: None,
            case: None,
            death: None,
            updated: None,
        }
    }
}
