/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CryptoSymbol {
    /// Symbol description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Display symbol name.
    #[serde(rename = "displaySymbol", skip_serializing_if = "Option::is_none")]
    pub display_symbol: Option<String>,
    /// Unique symbol used to identify this symbol used in <code>/crypto/candle</code> endpoint.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
}

impl CryptoSymbol {
    pub fn new() -> CryptoSymbol {
        CryptoSymbol {
            description: None,
            display_symbol: None,
            symbol: None,
        }
    }
}
