/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentResponse {
    /// AlphaResearch internal document id.
    #[serde(rename = "documentId", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    /// Title for this document.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Number of hit in this document
    #[serde(rename = "hits", skip_serializing_if = "Option::is_none")]
    pub hits: Option<String>,
    /// Link to render this document
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Format of this document (can be html or pdf)
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    /// Highlighted excerpts for this document
    #[serde(rename = "excerpts", skip_serializing_if = "Option::is_none")]
    pub excerpts: Option<Vec<models::ExcerptResponse>>,
}

impl DocumentResponse {
    pub fn new() -> DocumentResponse {
        DocumentResponse {
            document_id: None,
            title: None,
            hits: None,
            url: None,
            format: None,
            excerpts: None,
        }
    }
}
