/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EarningsCallLive {
    /// Array of earnings call events that support live streaming.
    #[serde(rename = "event", skip_serializing_if = "Option::is_none")]
    pub event: Option<Vec<models::EarningsCallLiveResult>>,
}

impl EarningsCallLive {
    pub fn new() -> EarningsCallLive {
        EarningsCallLive { event: None }
    }
}
