/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EarningsCallTranscripts {
    /// Company symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Transcript content.
    #[serde(rename = "transcript", skip_serializing_if = "Option::is_none")]
    pub transcript: Option<Vec<models::TranscriptContent>>,
    /// Participant list
    #[serde(rename = "participant", skip_serializing_if = "Option::is_none")]
    pub participant: Option<Vec<models::TranscriptParticipant>>,
    /// Audio link.
    #[serde(rename = "audio", skip_serializing_if = "Option::is_none")]
    pub audio: Option<String>,
    /// Transcript's ID.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Title.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Time of the event.
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    /// Year of earnings result in the case of earnings call transcript.
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i64>,
    /// Quarter of earnings result in the case of earnings call transcript.
    #[serde(rename = "quarter", skip_serializing_if = "Option::is_none")]
    pub quarter: Option<i64>,
}

impl EarningsCallTranscripts {
    pub fn new() -> EarningsCallTranscripts {
        EarningsCallTranscripts {
            symbol: None,
            transcript: None,
            participant: None,
            audio: None,
            id: None,
            title: None,
            time: None,
            year: None,
            quarter: None,
        }
    }
}
