/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EbitEstimatesInfo {
    /// Average EBIT estimates including Finnhub's proprietary estimates.
    #[serde(rename = "ebitAvg", skip_serializing_if = "Option::is_none")]
    pub ebit_avg: Option<f32>,
    /// Highest estimate.
    #[serde(rename = "ebitHigh", skip_serializing_if = "Option::is_none")]
    pub ebit_high: Option<f32>,
    /// Lowest estimate.
    #[serde(rename = "ebitLow", skip_serializing_if = "Option::is_none")]
    pub ebit_low: Option<f32>,
    /// Number of Analysts.
    #[serde(rename = "numberAnalysts", skip_serializing_if = "Option::is_none")]
    pub number_analysts: Option<i64>,
    /// Period.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
    /// Fiscal year.
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i64>,
    /// Fiscal quarter.
    #[serde(rename = "quarter", skip_serializing_if = "Option::is_none")]
    pub quarter: Option<i64>,
}

impl EbitEstimatesInfo {
    pub fn new() -> EbitEstimatesInfo {
        EbitEstimatesInfo {
            ebit_avg: None,
            ebit_high: None,
            ebit_low: None,
            number_analysts: None,
            period: None,
            year: None,
            quarter: None,
        }
    }
}
