/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmployeeCount {
    /// Date of the reading
    #[serde(rename = "atDate", skip_serializing_if = "Option::is_none")]
    pub at_date: Option<String>,
    /// Value
    #[serde(rename = "employee", skip_serializing_if = "Option::is_none")]
    pub employee: Option<f32>,
}

impl EmployeeCount {
    pub fn new() -> EmployeeCount {
        EmployeeCount {
            at_date: None,
            employee: None,
        }
    }
}
