/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EtfSectorExposureData {
    /// Industry
    #[serde(rename = "industry", skip_serializing_if = "Option::is_none")]
    pub industry: Option<String>,
    /// Percent of exposure.
    #[serde(rename = "exposure", skip_serializing_if = "Option::is_none")]
    pub exposure: Option<f32>,
}

impl EtfSectorExposureData {
    pub fn new() -> EtfSectorExposureData {
        EtfSectorExposureData {
            industry: None,
            exposure: None,
        }
    }
}
