/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EtfsCountryExposure {
    /// ETF symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Array of countries and and exposure levels.
    #[serde(rename = "countryExposure", skip_serializing_if = "Option::is_none")]
    pub country_exposure: Option<Vec<models::EtfCountryExposureData>>,
}

impl EtfsCountryExposure {
    pub fn new() -> EtfsCountryExposure {
        EtfsCountryExposure {
            symbol: None,
            country_exposure: None,
        }
    }
}
