/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExcerptResponse {
    /// Highlighted content
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Location of the content in the rendered document
    #[serde(rename = "snippetId", skip_serializing_if = "Option::is_none")]
    pub snippet_id: Option<String>,
    /// Start offset of highlighted content
    #[serde(rename = "startOffset", skip_serializing_if = "Option::is_none")]
    pub start_offset: Option<String>,
    /// End offset of highlighted content
    #[serde(rename = "endOffset", skip_serializing_if = "Option::is_none")]
    pub end_offset: Option<String>,
}

impl ExcerptResponse {
    pub fn new() -> ExcerptResponse {
        ExcerptResponse {
            content: None,
            snippet_id: None,
            start_offset: None,
            end_offset: None,
        }
    }
}
