/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Filing {
    /// Access number.
    #[serde(rename = "accessNumber", skip_serializing_if = "Option::is_none")]
    pub access_number: Option<String>,
    /// Symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// CIK.
    #[serde(rename = "cik", skip_serializing_if = "Option::is_none")]
    pub cik: Option<String>,
    /// Form type.
    #[serde(rename = "form", skip_serializing_if = "Option::is_none")]
    pub form: Option<String>,
    /// Filed date <code>%Y-%m-%d %H:%M:%S</code>.
    #[serde(rename = "filedDate", skip_serializing_if = "Option::is_none")]
    pub filed_date: Option<String>,
    /// Accepted date <code>%Y-%m-%d %H:%M:%S</code>.
    #[serde(rename = "acceptedDate", skip_serializing_if = "Option::is_none")]
    pub accepted_date: Option<String>,
    /// Report's URL.
    #[serde(rename = "reportUrl", skip_serializing_if = "Option::is_none")]
    pub report_url: Option<String>,
    /// Filing's URL.
    #[serde(rename = "filingUrl", skip_serializing_if = "Option::is_none")]
    pub filing_url: Option<String>,
}

impl Filing {
    pub fn new() -> Filing {
        Filing {
            access_number: None,
            symbol: None,
            cik: None,
            form: None,
            filed_date: None,
            accepted_date: None,
            report_url: None,
            filing_url: None,
        }
    }
}
