/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilingSentiment {
    /// % of negative words in the filing.
    #[serde(rename = "negative", skip_serializing_if = "Option::is_none")]
    pub negative: Option<f32>,
    /// % of positive words in the filing.
    #[serde(rename = "positive", skip_serializing_if = "Option::is_none")]
    pub positive: Option<f32>,
    /// % of polarity words in the filing.
    #[serde(rename = "polarity", skip_serializing_if = "Option::is_none")]
    pub polarity: Option<f32>,
    /// % of litigious words in the filing.
    #[serde(rename = "litigious", skip_serializing_if = "Option::is_none")]
    pub litigious: Option<f32>,
    /// % of uncertainty words in the filing.
    #[serde(rename = "uncertainty", skip_serializing_if = "Option::is_none")]
    pub uncertainty: Option<f32>,
    /// % of constraining words in the filing.
    #[serde(rename = "constraining", skip_serializing_if = "Option::is_none")]
    pub constraining: Option<f32>,
    /// % of modal-weak words in the filing.
    #[serde(rename = "modal-weak", skip_serializing_if = "Option::is_none")]
    pub modal_weak: Option<f32>,
    /// % of modal-strong words in the filing.
    #[serde(rename = "modal-strong", skip_serializing_if = "Option::is_none")]
    pub modal_strong: Option<f32>,
    /// % of modal-moderate words in the filing.
    #[serde(rename = "modal-moderate", skip_serializing_if = "Option::is_none")]
    pub modal_moderate: Option<f32>,
}

impl FilingSentiment {
    pub fn new() -> FilingSentiment {
        FilingSentiment {
            negative: None,
            positive: None,
            polarity: None,
            litigious: None,
            uncertainty: None,
            constraining: None,
            modal_weak: None,
            modal_strong: None,
            modal_moderate: None,
        }
    }
}
