/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilingResponse {
    /// Filing Id in Alpharesearch platform
    #[serde(rename = "filingId", skip_serializing_if = "Option::is_none")]
    pub filing_id: Option<String>,
    /// Filing title
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Id of the entity submitted the filing
    #[serde(rename = "filerId", skip_serializing_if = "Option::is_none")]
    pub filer_id: Option<String>,
    /// List of symbol associate with this filing
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<serde_json::Value>,
    /// Filer name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Date the filing is submitted.
    #[serde(rename = "acceptanceDate", skip_serializing_if = "Option::is_none")]
    pub acceptance_date: Option<String>,
    /// Date the filing is made available to the public
    #[serde(rename = "filedDate", skip_serializing_if = "Option::is_none")]
    pub filed_date: Option<String>,
    /// Date as which the filing is reported
    #[serde(rename = "reportDate", skip_serializing_if = "Option::is_none")]
    pub report_date: Option<String>,
    /// Filing Form
    #[serde(rename = "form", skip_serializing_if = "Option::is_none")]
    pub form: Option<String>,
    /// Amendment
    #[serde(rename = "amend", skip_serializing_if = "Option::is_none")]
    pub amend: Option<bool>,
    /// Filing Source
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// Estimate number of page when printing
    #[serde(rename = "pageCount", skip_serializing_if = "Option::is_none")]
    pub page_count: Option<i32>,
    /// Number of document in this filing
    #[serde(rename = "documentCount", skip_serializing_if = "Option::is_none")]
    pub document_count: Option<i32>,
}

impl FilingResponse {
    pub fn new() -> FilingResponse {
        FilingResponse {
            filing_id: None,
            title: None,
            filer_id: None,
            symbol: None,
            name: None,
            acceptance_date: None,
            filed_date: None,
            report_date: None,
            form: None,
            amend: None,
            source: None,
            page_count: None,
            document_count: None,
        }
    }
}
