/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FinancialStatements {
    /// Symbol of the company.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// An array of map of key, value pairs containing the data for each period.
    #[serde(rename = "financials", skip_serializing_if = "Option::is_none")]
    pub financials: Option<Vec<serde_json::Value>>,
}

impl FinancialStatements {
    pub fn new() -> FinancialStatements {
        FinancialStatements {
            symbol: None,
            financials: None,
        }
    }
}
