/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HistoricalNbbo {
    /// Symbol.
    #[serde(rename = "s", skip_serializing_if = "Option::is_none")]
    pub s: Option<String>,
    /// Number of ticks skipped.
    #[serde(rename = "skip", skip_serializing_if = "Option::is_none")]
    pub skip: Option<i64>,
    /// Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Total number of ticks for that date.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
    /// List of Ask volume data.
    #[serde(rename = "av", skip_serializing_if = "Option::is_none")]
    pub av: Option<Vec<f32>>,
    /// List of Ask price data.
    #[serde(rename = "a", skip_serializing_if = "Option::is_none")]
    pub a: Option<Vec<f32>>,
    /// List of venues/exchanges - Ask price. A list of exchange codes can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1Tj53M1svmr-hfEtbk6_NpVR1yAyGLMaH6ByYU6CG0ZY/edit?usp=sharing\",>here</a>
    #[serde(rename = "ax", skip_serializing_if = "Option::is_none")]
    pub ax: Option<Vec<String>>,
    /// List of Bid volume data.
    #[serde(rename = "bv", skip_serializing_if = "Option::is_none")]
    pub bv: Option<Vec<f32>>,
    /// List of Bid price data.
    #[serde(rename = "b", skip_serializing_if = "Option::is_none")]
    pub b: Option<Vec<f32>>,
    /// List of venues/exchanges - Bid price. A list of exchange codes can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1Tj53M1svmr-hfEtbk6_NpVR1yAyGLMaH6ByYU6CG0ZY/edit?usp=sharing\",>here</a>
    #[serde(rename = "bx", skip_serializing_if = "Option::is_none")]
    pub bx: Option<Vec<String>>,
    /// List of timestamp in UNIX ms.
    #[serde(rename = "t", skip_serializing_if = "Option::is_none")]
    pub t: Option<Vec<i64>>,
    /// List of quote conditions. A comprehensive list of quote conditions code can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1iiA6e7Osdtai0oPMOUzgAIKXCsay89dFDmsegz6OpEg/edit?usp=sharing\">here</a>
    #[serde(rename = "c", skip_serializing_if = "Option::is_none")]
    pub c: Option<Vec<Vec<String>>>,
}

impl HistoricalNbbo {
    pub fn new() -> HistoricalNbbo {
        HistoricalNbbo {
            s: None,
            skip: None,
            count: None,
            total: None,
            av: None,
            a: None,
            ax: None,
            bv: None,
            b: None,
            bx: None,
            t: None,
            c: None,
        }
    }
}
