/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Indicator {
    /// Number of buy signals
    #[serde(rename = "buy", skip_serializing_if = "Option::is_none")]
    pub buy: Option<i64>,
    /// Number of neutral signals
    #[serde(rename = "neutral", skip_serializing_if = "Option::is_none")]
    pub neutral: Option<i64>,
    /// Number of sell signals
    #[serde(rename = "sell", skip_serializing_if = "Option::is_none")]
    pub sell: Option<i64>,
}

impl Indicator {
    pub fn new() -> Indicator {
        Indicator {
            buy: None,
            neutral: None,
            sell: None,
        }
    }
}
