/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndicesHistoricalConstituents {
    /// Index's symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Array of historical constituents.
    #[serde(
        rename = "historicalConstituents",
        skip_serializing_if = "Option::is_none"
    )]
    pub historical_constituents: Option<Vec<models::IndexHistoricalConstituent>>,
}

impl IndicesHistoricalConstituents {
    pub fn new() -> IndicesHistoricalConstituents {
        IndicesHistoricalConstituents {
            symbol: None,
            historical_constituents: None,
        }
    }
}
