/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndicesConstituents {
    /// Index's symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Array of constituents.
    #[serde(rename = "constituents", skip_serializing_if = "Option::is_none")]
    pub constituents: Option<Vec<String>>,
    /// Array of constituents' details.
    #[serde(
        rename = "constituentsBreakdown",
        skip_serializing_if = "Option::is_none"
    )]
    pub constituents_breakdown: Option<Vec<models::IndicesConstituentsBreakdown>>,
}

impl IndicesConstituents {
    pub fn new() -> IndicesConstituents {
        IndicesConstituents {
            symbol: None,
            constituents: None,
            constituents_breakdown: None,
        }
    }
}
