/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndicesConstituentsBreakdown {
    /// Symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// ISIN.
    #[serde(rename = "isin", skip_serializing_if = "Option::is_none")]
    pub isin: Option<String>,
    /// Cusip.
    #[serde(rename = "cusip", skip_serializing_if = "Option::is_none")]
    pub cusip: Option<String>,
    /// Global Share Class FIGI.
    #[serde(rename = "shareClassFIGI", skip_serializing_if = "Option::is_none")]
    pub share_class_figi: Option<String>,
    /// Weight.
    #[serde(rename = "weight", skip_serializing_if = "Option::is_none")]
    pub weight: Option<f32>,
}

impl IndicesConstituentsBreakdown {
    pub fn new() -> IndicesConstituentsBreakdown {
        IndicesConstituentsBreakdown {
            symbol: None,
            name: None,
            isin: None,
            cusip: None,
            share_class_figi: None,
            weight: None,
        }
    }
}
