/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InsiderSentimentsData {
    /// Symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Year.
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i64>,
    /// Month.
    #[serde(rename = "month", skip_serializing_if = "Option::is_none")]
    pub month: Option<i64>,
    /// Net buying/selling from all insiders' transactions.
    #[serde(rename = "change", skip_serializing_if = "Option::is_none")]
    pub change: Option<i64>,
    /// Monthly share purchase ratio.
    #[serde(rename = "mspr", skip_serializing_if = "Option::is_none")]
    pub mspr: Option<f32>,
}

impl InsiderSentimentsData {
    pub fn new() -> InsiderSentimentsData {
        InsiderSentimentsData {
            symbol: None,
            year: None,
            month: None,
            change: None,
            mspr: None,
        }
    }
}
