/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstitutionalOwnershipInfo {
    /// Investor's company CIK.
    #[serde(rename = "cik", skip_serializing_if = "Option::is_none")]
    pub cik: Option<String>,
    /// Firm's name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// <code>put</code> or <code>call</code> for options.
    #[serde(rename = "putCall", skip_serializing_if = "Option::is_none")]
    pub put_call: Option<String>,
    /// Number of shares change.
    #[serde(rename = "change", skip_serializing_if = "Option::is_none")]
    pub change: Option<f32>,
    /// Number of shares with no voting rights.
    #[serde(rename = "noVoting", skip_serializing_if = "Option::is_none")]
    pub no_voting: Option<f32>,
    /// Percentage of portfolio.
    #[serde(rename = "percentage", skip_serializing_if = "Option::is_none")]
    pub percentage: Option<f32>,
    /// News score.
    #[serde(rename = "share", skip_serializing_if = "Option::is_none")]
    pub share: Option<f32>,
    /// Number of shares with shared voting rights.
    #[serde(rename = "sharedVoting", skip_serializing_if = "Option::is_none")]
    pub shared_voting: Option<f32>,
    /// Number of shares with sole voting rights.
    #[serde(rename = "soleVoting", skip_serializing_if = "Option::is_none")]
    pub sole_voting: Option<f32>,
    /// Position value.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f32>,
}

impl InstitutionalOwnershipInfo {
    pub fn new() -> InstitutionalOwnershipInfo {
        InstitutionalOwnershipInfo {
            cik: None,
            name: None,
            put_call: None,
            change: None,
            no_voting: None,
            percentage: None,
            share: None,
            shared_voting: None,
            sole_voting: None,
            value: None,
        }
    }
}
