/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstitutionalProfileInfo {
    /// Investor's company CIK.
    #[serde(rename = "cik", skip_serializing_if = "Option::is_none")]
    pub cik: Option<String>,
    /// Firm type.
    #[serde(rename = "firmType", skip_serializing_if = "Option::is_none")]
    pub firm_type: Option<String>,
    /// Manager.
    #[serde(rename = "manager", skip_serializing_if = "Option::is_none")]
    pub manager: Option<String>,
    /// Investing philosophy.
    #[serde(rename = "philosophy", skip_serializing_if = "Option::is_none")]
    pub philosophy: Option<String>,
    /// Profile info.
    #[serde(rename = "profile", skip_serializing_if = "Option::is_none")]
    pub profile: Option<String>,
    /// Profile image.
    #[serde(rename = "profileImg", skip_serializing_if = "Option::is_none")]
    pub profile_img: Option<String>,
}

impl InstitutionalProfileInfo {
    pub fn new() -> InstitutionalProfileInfo {
        InstitutionalProfileInfo {
            cik: None,
            firm_type: None,
            manager: None,
            philosophy: None,
            profile: None,
            profile_img: None,
        }
    }
}
