/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstitutionalPortfolioGroup {
    /// Report date.
    #[serde(rename = "reportDate", skip_serializing_if = "Option::is_none")]
    pub report_date: Option<String>,
    /// Filing date.
    #[serde(rename = "filingDate", skip_serializing_if = "Option::is_none")]
    pub filing_date: Option<String>,
    /// Array of positions.
    #[serde(rename = "portfolio", skip_serializing_if = "Option::is_none")]
    pub portfolio: Option<Vec<models::InstitutionalPortfolioInfo>>,
}

impl InstitutionalPortfolioGroup {
    pub fn new() -> InstitutionalPortfolioGroup {
        InstitutionalPortfolioGroup {
            report_date: None,
            filing_date: None,
            portfolio: None,
        }
    }
}
