/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InstitutionalOwnershipGroup {
    /// Report date.
    #[serde(rename = "reportDate", skip_serializing_if = "Option::is_none")]
    pub report_date: Option<String>,
    /// Array of institutional investors.
    #[serde(rename = "ownership", skip_serializing_if = "Option::is_none")]
    pub ownership: Option<Vec<models::InstitutionalOwnershipInfo>>,
}

impl InstitutionalOwnershipGroup {
    pub fn new() -> InstitutionalOwnershipGroup {
        InstitutionalOwnershipGroup {
            report_date: None,
            ownership: None,
        }
    }
}
