/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IpoCalendar {
    /// Array of IPO events.
    #[serde(rename = "ipoCalendar", skip_serializing_if = "Option::is_none")]
    pub ipo_calendar: Option<Vec<models::IpoEvent>>,
}

impl IpoCalendar {
    pub fn new() -> IpoCalendar {
        IpoCalendar { ipo_calendar: None }
    }
}
