/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IsinChangeInfo {
    /// Event's date.
    #[serde(rename = "atDate", skip_serializing_if = "Option::is_none")]
    pub at_date: Option<String>,
    /// Old ISIN.
    #[serde(rename = "oldIsin", skip_serializing_if = "Option::is_none")]
    pub old_isin: Option<String>,
    /// New ISIN.
    #[serde(rename = "newIsin", skip_serializing_if = "Option::is_none")]
    pub new_isin: Option<String>,
}

impl IsinChangeInfo {
    pub fn new() -> IsinChangeInfo {
        IsinChangeInfo {
            at_date: None,
            old_isin: None,
            new_isin: None,
        }
    }
}
