/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyCustomersSuppliers {
    /// Symbol
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Country
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Industry
    #[serde(rename = "industry", skip_serializing_if = "Option::is_none")]
    pub industry: Option<String>,
    /// Whether the company is a customer.
    #[serde(rename = "customer", skip_serializing_if = "Option::is_none")]
    pub customer: Option<bool>,
    /// Whether the company is a supplier
    #[serde(rename = "supplier", skip_serializing_if = "Option::is_none")]
    pub supplier: Option<bool>,
    /// 1-month price correlation
    #[serde(
        rename = "oneMonthCorrelation",
        skip_serializing_if = "Option::is_none"
    )]
    pub one_month_correlation: Option<f32>,
    /// 1-year price correlation
    #[serde(rename = "oneYearCorrelation", skip_serializing_if = "Option::is_none")]
    pub one_year_correlation: Option<f32>,
    /// 6-month price correlation
    #[serde(
        rename = "sixMonthCorrelation",
        skip_serializing_if = "Option::is_none"
    )]
    pub six_month_correlation: Option<f32>,
    /// 3-month price correlation
    #[serde(
        rename = "threeMonthCorrelation",
        skip_serializing_if = "Option::is_none"
    )]
    pub three_month_correlation: Option<f32>,
    /// 2-week price correlation
    #[serde(rename = "twoWeekCorrelation", skip_serializing_if = "Option::is_none")]
    pub two_week_correlation: Option<f32>,
    /// 2-year price correlation
    #[serde(rename = "twoYearCorrelation", skip_serializing_if = "Option::is_none")]
    pub two_year_correlation: Option<f32>,
}

impl KeyCustomersSuppliers {
    pub fn new() -> KeyCustomersSuppliers {
        KeyCustomersSuppliers {
            symbol: None,
            name: None,
            country: None,
            industry: None,
            customer: None,
            supplier: None,
            one_month_correlation: None,
            one_year_correlation: None,
            six_month_correlation: None,
            three_month_correlation: None,
            two_week_correlation: None,
            two_year_correlation: None,
        }
    }
}
