/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LobbyingData {
    /// Symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Company's name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Description.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Country.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Year.
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i64>,
    /// Period.
    #[serde(rename = "period", skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
    /// Income reported by lobbying firms.
    #[serde(rename = "income", skip_serializing_if = "Option::is_none")]
    pub income: Option<f32>,
    /// Expenses reported by the company.
    #[serde(rename = "expenses", skip_serializing_if = "Option::is_none")]
    pub expenses: Option<f32>,
    /// Document's URL.
    #[serde(rename = "documentUrl", skip_serializing_if = "Option::is_none")]
    pub document_url: Option<String>,
    /// Posted name.
    #[serde(rename = "postedName", skip_serializing_if = "Option::is_none")]
    pub posted_name: Option<String>,
    /// Date.
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// Client ID.
    #[serde(rename = "clientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Registrant ID.
    #[serde(rename = "registrantId", skip_serializing_if = "Option::is_none")]
    pub registrant_id: Option<String>,
    /// Senate ID.
    #[serde(rename = "senateId", skip_serializing_if = "Option::is_none")]
    pub senate_id: Option<String>,
    /// House registrant ID.
    #[serde(rename = "houseregistrantId", skip_serializing_if = "Option::is_none")]
    pub houseregistrant_id: Option<String>,
}

impl LobbyingData {
    pub fn new() -> LobbyingData {
        LobbyingData {
            symbol: None,
            name: None,
            description: None,
            country: None,
            year: None,
            period: None,
            income: None,
            expenses: None,
            document_url: None,
            posted_name: None,
            date: None,
            client_id: None,
            registrant_id: None,
            senate_id: None,
            houseregistrant_id: None,
        }
    }
}
