/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketNews {
    /// News category.
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Published time in UNIX timestamp.
    #[serde(rename = "datetime", skip_serializing_if = "Option::is_none")]
    pub datetime: Option<i64>,
    /// News headline.
    #[serde(rename = "headline", skip_serializing_if = "Option::is_none")]
    pub headline: Option<String>,
    /// News ID. This value can be used for <code>minId</code> params to get the latest news only.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Thumbnail image URL.
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    /// Related stocks and companies mentioned in the article.
    #[serde(rename = "related", skip_serializing_if = "Option::is_none")]
    pub related: Option<String>,
    /// News source.
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// News summary.
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// URL of the original article.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl MarketNews {
    pub fn new() -> MarketNews {
        MarketNews {
            category: None,
            datetime: None,
            headline: None,
            id: None,
            image: None,
            related: None,
            source: None,
            summary: None,
            url: None,
        }
    }
}
