/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketStatus {
    /// Exchange.
    #[serde(rename = "exchange", skip_serializing_if = "Option::is_none")]
    pub exchange: Option<String>,
    /// Timezone.
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Market session. Can be 1 of the following values: <code>pre-market</code>,<code>regular</code>,<code>post-market</code> or <code>null</code> if the market is closed.
    #[serde(rename = "session", skip_serializing_if = "Option::is_none")]
    pub session: Option<String>,
    /// Holiday event.
    #[serde(rename = "holiday", skip_serializing_if = "Option::is_none")]
    pub holiday: Option<String>,
    /// Whether the market is open at the moment.
    #[serde(rename = "isOpen", skip_serializing_if = "Option::is_none")]
    pub is_open: Option<bool>,
    /// Current timestamp.
    #[serde(rename = "t", skip_serializing_if = "Option::is_none")]
    pub t: Option<i64>,
}

impl MarketStatus {
    pub fn new() -> MarketStatus {
        MarketStatus {
            exchange: None,
            timezone: None,
            session: None,
            holiday: None,
            is_open: None,
            t: None,
        }
    }
}
