/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MarketHolidayData {
    /// Holiday's name.
    #[serde(rename = "eventName", skip_serializing_if = "Option::is_none")]
    pub event_name: Option<String>,
    /// Date.
    #[serde(rename = "atDate", skip_serializing_if = "Option::is_none")]
    pub at_date: Option<String>,
    /// Trading hours for this day if the market is partially closed only.
    #[serde(rename = "tradingHour", skip_serializing_if = "Option::is_none")]
    pub trading_hour: Option<String>,
}

impl MarketHolidayData {
    pub fn new() -> MarketHolidayData {
        MarketHolidayData {
            event_name: None,
            at_date: None,
            trading_hour: None,
        }
    }
}
