/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MutualFundProfileData {
    /// Name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Fund's category.
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    /// Investment Segment.
    #[serde(rename = "investmentSegment", skip_serializing_if = "Option::is_none")]
    pub investment_segment: Option<String>,
    /// NAV.
    #[serde(rename = "totalNav", skip_serializing_if = "Option::is_none")]
    pub total_nav: Option<f32>,
    /// Expense ratio.
    #[serde(rename = "expenseRatio", skip_serializing_if = "Option::is_none")]
    pub expense_ratio: Option<f32>,
    /// Index benchmark.
    #[serde(rename = "benchmark", skip_serializing_if = "Option::is_none")]
    pub benchmark: Option<String>,
    /// Inception date.
    #[serde(rename = "inceptionDate", skip_serializing_if = "Option::is_none")]
    pub inception_date: Option<String>,
    /// Fund's description.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Fund Family.
    #[serde(rename = "fundFamily", skip_serializing_if = "Option::is_none")]
    pub fund_family: Option<String>,
    /// Fund Company.
    #[serde(rename = "fundCompany", skip_serializing_if = "Option::is_none")]
    pub fund_company: Option<String>,
    /// Fund's managers.
    #[serde(rename = "manager", skip_serializing_if = "Option::is_none")]
    pub manager: Option<String>,
    /// Status.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Beta.
    #[serde(rename = "beta", skip_serializing_if = "Option::is_none")]
    pub beta: Option<f32>,
    /// Deferred load.
    #[serde(rename = "deferredLoad", skip_serializing_if = "Option::is_none")]
    pub deferred_load: Option<f32>,
    /// 12B-1 fee.
    #[serde(rename = "fee12b1", skip_serializing_if = "Option::is_none")]
    pub fee12b1: Option<f32>,
    /// Front Load.
    #[serde(rename = "frontLoad", skip_serializing_if = "Option::is_none")]
    pub front_load: Option<f32>,
    /// IRA minimum investment.
    #[serde(rename = "iraMinInvestment", skip_serializing_if = "Option::is_none")]
    pub ira_min_investment: Option<f32>,
    /// ISIN.
    #[serde(rename = "isin", skip_serializing_if = "Option::is_none")]
    pub isin: Option<String>,
    /// CUSIP.
    #[serde(rename = "cusip", skip_serializing_if = "Option::is_none")]
    pub cusip: Option<String>,
    /// Max redemption fee.
    #[serde(rename = "maxRedemptionFee", skip_serializing_if = "Option::is_none")]
    pub max_redemption_fee: Option<f32>,
    /// Minimum investment for standard accounts.
    #[serde(
        rename = "standardMinInvestment",
        skip_serializing_if = "Option::is_none"
    )]
    pub standard_min_investment: Option<f32>,
    /// Turnover.
    #[serde(rename = "turnover", skip_serializing_if = "Option::is_none")]
    pub turnover: Option<f32>,
    /// Fund's series ID. This field can be used to group multiple share classes into 1 unique fund.
    #[serde(rename = "seriesId", skip_serializing_if = "Option::is_none")]
    pub series_id: Option<String>,
    /// Fund's series name.
    #[serde(rename = "seriesName", skip_serializing_if = "Option::is_none")]
    pub series_name: Option<String>,
    /// Class ID.
    #[serde(rename = "classId", skip_serializing_if = "Option::is_none")]
    pub class_id: Option<String>,
    /// Class name.
    #[serde(rename = "className", skip_serializing_if = "Option::is_none")]
    pub class_name: Option<String>,
    /// SFDR classification for EU funds. Under the new classifications, a fund's strategy will labeled under either Article 6, 8 or 9. Article 6 covers funds which do not integrate any kind of sustainability into the investment process. Article 8, also known as ‘environmental and socially promoting’, applies “… where a financial product promotes, among other characteristics, environmental or social characteristics, or a combination of those characteristics, provided that the companies in which the investments are made follow good governance practices.”. Article 9, also known as ‘products targeting sustainable investments’, covers products targeting bespoke sustainable investments and applies “… where a financial product has sustainable investment as its objective and an index has been designated as a reference benchmark.”
    #[serde(rename = "sfdrClassification", skip_serializing_if = "Option::is_none")]
    pub sfdr_classification: Option<String>,
    /// Fund's currency
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
}

impl MutualFundProfileData {
    pub fn new() -> MutualFundProfileData {
        MutualFundProfileData {
            name: None,
            category: None,
            investment_segment: None,
            total_nav: None,
            expense_ratio: None,
            benchmark: None,
            inception_date: None,
            description: None,
            fund_family: None,
            fund_company: None,
            manager: None,
            status: None,
            beta: None,
            deferred_load: None,
            fee12b1: None,
            front_load: None,
            ira_min_investment: None,
            isin: None,
            cusip: None,
            max_redemption_fee: None,
            standard_min_investment: None,
            turnover: None,
            series_id: None,
            series_name: None,
            class_id: None,
            class_name: None,
            sfdr_classification: None,
            currency: None,
        }
    }
}
