/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MutualFundSectorExposure {
    /// Mutual symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Array of sector and exposure levels.
    #[serde(rename = "sectorExposure", skip_serializing_if = "Option::is_none")]
    pub sector_exposure: Option<Vec<models::MutualFundSectorExposureData>>,
}

impl MutualFundSectorExposure {
    pub fn new() -> MutualFundSectorExposure {
        MutualFundSectorExposure {
            symbol: None,
            sector_exposure: None,
        }
    }
}
