/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewsroomArticle {
    /// Published time in <code>YYYY-MM-DD HH:MM:SS</code> format (EST timezone).
    #[serde(rename = "atDate", skip_serializing_if = "Option::is_none")]
    pub at_date: Option<String>,
    /// Title.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// URL to download the full text data.
    #[serde(rename = "fullText", skip_serializing_if = "Option::is_none")]
    pub full_text: Option<String>,
    /// Original URL.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl NewsroomArticle {
    pub fn new() -> NewsroomArticle {
        NewsroomArticle {
            at_date: None,
            title: None,
            full_text: None,
            url: None,
        }
    }
}
