/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ownership {
    /// Symbol of the company.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Array of investors with detailed information about their holdings.
    #[serde(rename = "ownership", skip_serializing_if = "Option::is_none")]
    pub ownership: Option<Vec<models::OwnershipInfo>>,
}

impl Ownership {
    pub fn new() -> Ownership {
        Ownership {
            symbol: None,
            ownership: None,
        }
    }
}
