/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OwnershipInfo {
    /// Investor's name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Number of shares held by the investor.
    #[serde(rename = "share", skip_serializing_if = "Option::is_none")]
    pub share: Option<i64>,
    /// Number of share changed (net buy or sell) from the last period.
    #[serde(rename = "change", skip_serializing_if = "Option::is_none")]
    pub change: Option<i64>,
    /// Filing date.
    #[serde(rename = "filingDate", skip_serializing_if = "Option::is_none")]
    pub filing_date: Option<String>,
}

impl OwnershipInfo {
    pub fn new() -> OwnershipInfo {
        OwnershipInfo {
            name: None,
            share: None,
            change: None,
            filing_date: None,
        }
    }
}
