/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatternRecognition {
    /// Array of patterns.
    #[serde(rename = "points", skip_serializing_if = "Option::is_none")]
    pub points: Option<Vec<serde_json::Value>>,
}

impl PatternRecognition {
    pub fn new() -> PatternRecognition {
        PatternRecognition { points: None }
    }
}
