/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriceMetrics {
    /// Symbol of the company.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Data date.
    #[serde(rename = "atDate", skip_serializing_if = "Option::is_none")]
    pub at_date: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
}

impl PriceMetrics {
    pub fn new() -> PriceMetrics {
        PriceMetrics {
            symbol: None,
            at_date: None,
            data: None,
        }
    }
}
