/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Quote {
    /// Open price of the day
    #[serde(rename = "o", skip_serializing_if = "Option::is_none")]
    pub o: Option<f32>,
    /// High price of the day
    #[serde(rename = "h", skip_serializing_if = "Option::is_none")]
    pub h: Option<f32>,
    /// Low price of the day
    #[serde(rename = "l", skip_serializing_if = "Option::is_none")]
    pub l: Option<f32>,
    /// Current price
    #[serde(rename = "c", skip_serializing_if = "Option::is_none")]
    pub c: Option<f32>,
    /// Previous close price
    #[serde(rename = "pc", skip_serializing_if = "Option::is_none")]
    pub pc: Option<f32>,
    /// Change
    #[serde(rename = "d", skip_serializing_if = "Option::is_none")]
    pub d: Option<f32>,
    /// Percent change
    #[serde(rename = "dp", skip_serializing_if = "Option::is_none")]
    pub dp: Option<f32>,
}

impl Quote {
    pub fn new() -> Quote {
        Quote {
            o: None,
            h: None,
            l: None,
            c: None,
            pc: None,
            d: None,
            dp: None,
        }
    }
}
