/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Report {
    /// Access number.
    #[serde(rename = "accessNumber", skip_serializing_if = "Option::is_none")]
    pub access_number: Option<String>,
    /// Symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// CIK.
    #[serde(rename = "cik", skip_serializing_if = "Option::is_none")]
    pub cik: Option<String>,
    /// Year.
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i64>,
    /// Quarter.
    #[serde(rename = "quarter", skip_serializing_if = "Option::is_none")]
    pub quarter: Option<i64>,
    /// Form type.
    #[serde(rename = "form", skip_serializing_if = "Option::is_none")]
    pub form: Option<String>,
    /// Period start date <code>%Y-%m-%d %H:%M:%S</code>.
    #[serde(rename = "startDate", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    /// Period end date <code>%Y-%m-%d %H:%M:%S</code>.
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    /// Filed date <code>%Y-%m-%d %H:%M:%S</code>.
    #[serde(rename = "filedDate", skip_serializing_if = "Option::is_none")]
    pub filed_date: Option<String>,
    /// Accepted date <code>%Y-%m-%d %H:%M:%S</code>.
    #[serde(rename = "acceptedDate", skip_serializing_if = "Option::is_none")]
    pub accepted_date: Option<String>,
    #[serde(rename = "report", skip_serializing_if = "Option::is_none")]
    pub report: Option<serde_json::Value>,
}

impl Report {
    pub fn new() -> Report {
        Report {
            access_number: None,
            symbol: None,
            cik: None,
            year: None,
            quarter: None,
            form: None,
            start_date: None,
            end_date: None,
            filed_date: None,
            accepted_date: None,
            report: None,
        }
    }
}
