/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchResponse {
    /// Total filing matched your search criteria.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    /// Time took to execute your search query on our server, value in ms.
    #[serde(rename = "took", skip_serializing_if = "Option::is_none")]
    pub took: Option<i32>,
    /// Current search page
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    /// Filing match your search criteria.
    #[serde(rename = "filings", skip_serializing_if = "Option::is_none")]
    pub filings: Option<Vec<models::FilingResponse>>,
}

impl SearchResponse {
    pub fn new() -> SearchResponse {
        SearchResponse {
            count: None,
            took: None,
            page: None,
            filings: None,
        }
    }
}
