/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchBody {
    /// Search query
    #[serde(rename = "query")]
    pub query: String,
    /// List of isin to search, comma separated (Max: 50).
    #[serde(rename = "isins", skip_serializing_if = "Option::is_none")]
    pub isins: Option<String>,
    /// List of cusip to search, comma separated (Max: 50).
    #[serde(rename = "cusips", skip_serializing_if = "Option::is_none")]
    pub cusips: Option<String>,
    /// List of SEC Center Index Key to search, comma separated (Max: 50).
    #[serde(rename = "ciks", skip_serializing_if = "Option::is_none")]
    pub ciks: Option<String>,
    /// List of SEDAR issuer number to search, comma separated (Max: 50).
    #[serde(rename = "sedarIds", skip_serializing_if = "Option::is_none")]
    pub sedar_ids: Option<String>,
    /// List of Companies House number to search, comma separated (Max: 50).
    #[serde(rename = "chIds", skip_serializing_if = "Option::is_none")]
    pub ch_ids: Option<String>,
    /// List of symbols to search, comma separated (Max: 50).
    #[serde(rename = "symbols", skip_serializing_if = "Option::is_none")]
    pub symbols: Option<String>,
    /// List of sedols to search, comma separated (Max: 50).
    #[serde(rename = "sedols", skip_serializing_if = "Option::is_none")]
    pub sedols: Option<String>,
    /// List of sources to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values.
    #[serde(rename = "sources", skip_serializing_if = "Option::is_none")]
    pub sources: Option<String>,
    /// List of forms to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values.
    #[serde(rename = "forms", skip_serializing_if = "Option::is_none")]
    pub forms: Option<String>,
    /// List of gics to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values.
    #[serde(rename = "gics", skip_serializing_if = "Option::is_none")]
    pub gics: Option<String>,
    /// List of sources to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values.
    #[serde(rename = "naics", skip_serializing_if = "Option::is_none")]
    pub naics: Option<String>,
    /// List of exhibits to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values.
    #[serde(rename = "exhibits", skip_serializing_if = "Option::is_none")]
    pub exhibits: Option<String>,
    /// List of exchanges to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values.
    #[serde(rename = "exchanges", skip_serializing_if = "Option::is_none")]
    pub exchanges: Option<String>,
    /// List of sources to search, comma separated (Max: 50). Look at <code>/filter</code> endpoint to see all available values.
    #[serde(rename = "countries", skip_serializing_if = "Option::is_none")]
    pub countries: Option<String>,
    /// List of SEC's exchanges act to search, comma separated. Look at <code>/filter</code> endpoint to see all available values.
    #[serde(rename = "acts", skip_serializing_if = "Option::is_none")]
    pub acts: Option<String>,
    /// List of market capitalization to search, comma separated. Look at <code>/filter</code> endpoint to see all available values.
    #[serde(rename = "caps", skip_serializing_if = "Option::is_none")]
    pub caps: Option<String>,
    /// Search from date in format: YYYY-MM-DD, default from the last 2 years
    #[serde(rename = "fromDate", skip_serializing_if = "Option::is_none")]
    pub from_date: Option<String>,
    /// Search to date in format: YYYY-MM-DD, default to today
    #[serde(rename = "toDate", skip_serializing_if = "Option::is_none")]
    pub to_date: Option<String>,
    /// Use for pagination, default to page 1
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<String>,
    /// Sort result by, default: sortMostRecent. Look at <code>/filter</code> endpoint to see all available values.
    #[serde(rename = "sort", skip_serializing_if = "Option::is_none")]
    pub sort: Option<String>,
    /// Enable highlight in returned filings. If enabled, only return 10 results each time
    #[serde(rename = "highlighted", skip_serializing_if = "Option::is_none")]
    pub highlighted: Option<bool>,
}

impl SearchBody {
    pub fn new(query: String) -> SearchBody {
        SearchBody {
            query,
            isins: None,
            cusips: None,
            ciks: None,
            sedar_ids: None,
            ch_ids: None,
            symbols: None,
            sedols: None,
            sources: None,
            forms: None,
            gics: None,
            naics: None,
            exhibits: None,
            exchanges: None,
            countries: None,
            acts: None,
            caps: None,
            from_date: None,
            to_date: None,
            page: None,
            sort: None,
            highlighted: None,
        }
    }
}
