/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SectorMetricData {
    /// Sector
    #[serde(rename = "sector", skip_serializing_if = "Option::is_none")]
    pub sector: Option<String>,
    /// Metrics data in key-value format. <code>a</code> and <code>m</code> fields are for average and median respectively.
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<serde_json::Value>,
}

impl SectorMetricData {
    pub fn new() -> SectorMetricData {
        SectorMetricData {
            sector: None,
            metrics: None,
        }
    }
}
