/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Sentiment {
    ///
    #[serde(rename = "bearishPercent", skip_serializing_if = "Option::is_none")]
    pub bearish_percent: Option<f32>,
    ///
    #[serde(rename = "bullishPercent", skip_serializing_if = "Option::is_none")]
    pub bullish_percent: Option<f32>,
}

impl Sentiment {
    pub fn new() -> Sentiment {
        Sentiment {
            bearish_percent: None,
            bullish_percent: None,
        }
    }
}
