/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SimilarityIndex {
    /// Symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// CIK.
    #[serde(rename = "cik", skip_serializing_if = "Option::is_none")]
    pub cik: Option<String>,
    /// Array of filings with its cosine similarity compared to the same report of the previous year.
    #[serde(rename = "similarity", skip_serializing_if = "Option::is_none")]
    pub similarity: Option<Vec<models::SimilarityIndexInfo>>,
}

impl SimilarityIndex {
    pub fn new() -> SimilarityIndex {
        SimilarityIndex {
            symbol: None,
            cik: None,
            similarity: None,
        }
    }
}
