/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Split {
    /// Symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Split date.
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// From factor.
    #[serde(rename = "fromFactor", skip_serializing_if = "Option::is_none")]
    pub from_factor: Option<f32>,
    /// To factor.
    #[serde(rename = "toFactor", skip_serializing_if = "Option::is_none")]
    pub to_factor: Option<f32>,
}

impl Split {
    pub fn new() -> Split {
        Split {
            symbol: None,
            date: None,
            from_factor: None,
            to_factor: None,
        }
    }
}
