/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StockTranscripts {
    /// Transcript's ID used to get the <a href=\"#transcripts\">full transcript</a>.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Title.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Time of the event.
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    /// Year of earnings result in the case of earnings call transcript.
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i64>,
    /// Quarter of earnings result in the case of earnings call transcript.
    #[serde(rename = "quarter", skip_serializing_if = "Option::is_none")]
    pub quarter: Option<i64>,
}

impl StockTranscripts {
    pub fn new() -> StockTranscripts {
        StockTranscripts {
            id: None,
            title: None,
            time: None,
            year: None,
            quarter: None,
        }
    }
}
