/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StockCandles {
    /// List of open prices for returned candles.
    #[serde(rename = "o", skip_serializing_if = "Option::is_none")]
    pub o: Option<Vec<f32>>,
    /// List of high prices for returned candles.
    #[serde(rename = "h", skip_serializing_if = "Option::is_none")]
    pub h: Option<Vec<f32>>,
    /// List of low prices for returned candles.
    #[serde(rename = "l", skip_serializing_if = "Option::is_none")]
    pub l: Option<Vec<f32>>,
    /// List of close prices for returned candles.
    #[serde(rename = "c", skip_serializing_if = "Option::is_none")]
    pub c: Option<Vec<f32>>,
    /// List of volume data for returned candles.
    #[serde(rename = "v", skip_serializing_if = "Option::is_none")]
    pub v: Option<Vec<f32>>,
    /// List of timestamp for returned candles.
    #[serde(rename = "t", skip_serializing_if = "Option::is_none")]
    pub t: Option<Vec<i64>>,
    /// Status of the response. This field can either be ok or no_data.
    #[serde(rename = "s", skip_serializing_if = "Option::is_none")]
    pub s: Option<String>,
}

impl StockCandles {
    pub fn new() -> StockCandles {
        StockCandles {
            o: None,
            h: None,
            l: None,
            c: None,
            v: None,
            t: None,
            s: None,
        }
    }
}
