/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StockPresentation {
    /// Company symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Presentation data.
    #[serde(rename = "res", skip_serializing_if = "Option::is_none")]
    pub res: Option<Vec<models::PresentationData>>,
}

impl StockPresentation {
    pub fn new() -> StockPresentation {
        StockPresentation {
            symbol: None,
            res: None,
        }
    }
}
