/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StockSymbol {
    /// Symbol description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Display symbol name.
    #[serde(rename = "displaySymbol", skip_serializing_if = "Option::is_none")]
    pub display_symbol: Option<String>,
    /// Unique symbol used to identify this symbol used in <code>/stock/candle</code> endpoint.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Security type.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Primary exchange's MIC.
    #[serde(rename = "mic", skip_serializing_if = "Option::is_none")]
    pub mic: Option<String>,
    /// FIGI identifier.
    #[serde(rename = "figi", skip_serializing_if = "Option::is_none")]
    pub figi: Option<String>,
    /// Global Share Class FIGI.
    #[serde(rename = "shareClassFIGI", skip_serializing_if = "Option::is_none")]
    pub share_class_figi: Option<String>,
    /// Price's currency. This might be different from the reporting currency of fundamental data.
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    /// Alternative ticker for exchanges with multiple tickers for 1 stock such as BSE.
    #[serde(rename = "symbol2", skip_serializing_if = "Option::is_none")]
    pub symbol2: Option<String>,
    /// ISIN. This field is only available for EU stocks and selected Asian markets. Entitlement from Finnhub is required to access this field.
    #[serde(rename = "isin", skip_serializing_if = "Option::is_none")]
    pub isin: Option<String>,
}

impl StockSymbol {
    pub fn new() -> StockSymbol {
        StockSymbol {
            description: None,
            display_symbol: None,
            symbol: None,
            r#type: None,
            mic: None,
            figi: None,
            share_class_figi: None,
            currency: None,
            symbol2: None,
            isin: None,
        }
    }
}
