/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SymbolChangeInfo {
    /// Event's date.
    #[serde(rename = "atDate", skip_serializing_if = "Option::is_none")]
    pub at_date: Option<String>,
    /// Old symbol.
    #[serde(rename = "oldSymbol", skip_serializing_if = "Option::is_none")]
    pub old_symbol: Option<String>,
    /// New symbol.
    #[serde(rename = "newSymbol", skip_serializing_if = "Option::is_none")]
    pub new_symbol: Option<String>,
}

impl SymbolChangeInfo {
    pub fn new() -> SymbolChangeInfo {
        SymbolChangeInfo {
            at_date: None,
            old_symbol: None,
            new_symbol: None,
        }
    }
}
