/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TickData {
    /// Symbol.
    #[serde(rename = "s", skip_serializing_if = "Option::is_none")]
    pub s: Option<String>,
    /// Number of ticks skipped.
    #[serde(rename = "skip", skip_serializing_if = "Option::is_none")]
    pub skip: Option<i64>,
    /// Number of ticks returned. If <code>count</code> < <code>limit</code>, all data for that date has been returned.
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i64>,
    /// Total number of ticks for that date.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
    /// List of volume data.
    #[serde(rename = "v", skip_serializing_if = "Option::is_none")]
    pub v: Option<Vec<f32>>,
    /// List of price data.
    #[serde(rename = "p", skip_serializing_if = "Option::is_none")]
    pub p: Option<Vec<f32>>,
    /// List of timestamp in UNIX ms.
    #[serde(rename = "t", skip_serializing_if = "Option::is_none")]
    pub t: Option<Vec<i64>>,
    /// List of venues/exchanges. A list of exchange codes can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1Tj53M1svmr-hfEtbk6_NpVR1yAyGLMaH6ByYU6CG0ZY/edit?usp=sharing\",>here</a>
    #[serde(rename = "x", skip_serializing_if = "Option::is_none")]
    pub x: Option<Vec<String>>,
    /// List of trade conditions. A comprehensive list of trade conditions code can be found <a target=\"_blank\" href=\"https://docs.google.com/spreadsheets/d/1PUxiSWPHSODbaTaoL2Vef6DgU-yFtlRGZf19oBb9Hp0/edit?usp=sharing\">here</a>
    #[serde(rename = "c", skip_serializing_if = "Option::is_none")]
    pub c: Option<Vec<Vec<String>>>,
}

impl TickData {
    pub fn new() -> TickData {
        TickData {
            s: None,
            skip: None,
            count: None,
            total: None,
            v: None,
            p: None,
            t: None,
            x: None,
            c: None,
        }
    }
}
