/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transactions {
    /// Symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Insider's name.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Number of shares held after the transaction.
    #[serde(rename = "share", skip_serializing_if = "Option::is_none")]
    pub share: Option<i64>,
    /// Number of share changed from the last period. A positive value suggests a <code>BUY</code> transaction. A negative value suggests a <code>SELL</code> transaction.
    #[serde(rename = "change", skip_serializing_if = "Option::is_none")]
    pub change: Option<i64>,
    /// Filing date.
    #[serde(rename = "filingDate", skip_serializing_if = "Option::is_none")]
    pub filing_date: Option<String>,
    /// Transaction date.
    #[serde(rename = "transactionDate", skip_serializing_if = "Option::is_none")]
    pub transaction_date: Option<String>,
    /// Average transaction price.
    #[serde(rename = "transactionPrice", skip_serializing_if = "Option::is_none")]
    pub transaction_price: Option<f32>,
    /// Transaction code. A list of codes and their meanings can be found <a href=\"https://www.sec.gov/about/forms/form4data.pdf\" target=\"_blank\" rel=\"noopener\">here</a>.
    #[serde(rename = "transactionCode", skip_serializing_if = "Option::is_none")]
    pub transaction_code: Option<String>,
}

impl Transactions {
    pub fn new() -> Transactions {
        Transactions {
            symbol: None,
            name: None,
            share: None,
            change: None,
            filing_date: None,
            transaction_date: None,
            transaction_price: None,
            transaction_code: None,
        }
    }
}
