/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TranscriptContent {
    /// Speaker's name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Speaker's speech
    #[serde(rename = "speech", skip_serializing_if = "Option::is_none")]
    pub speech: Option<Vec<String>>,
    /// Earnings calls section (management discussion or Q&A)
    #[serde(rename = "session", skip_serializing_if = "Option::is_none")]
    pub session: Option<String>,
}

impl TranscriptContent {
    pub fn new() -> TranscriptContent {
        TranscriptContent {
            name: None,
            speech: None,
            session: None,
        }
    }
}
