/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Trend {
    /// ADX reading
    #[serde(rename = "adx", skip_serializing_if = "Option::is_none")]
    pub adx: Option<f32>,
    /// Whether market is trending or going sideway
    #[serde(rename = "trending", skip_serializing_if = "Option::is_none")]
    pub trending: Option<bool>,
}

impl Trend {
    pub fn new() -> Trend {
        Trend {
            adx: None,
            trending: None,
        }
    }
}
