/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsaSpending {
    /// Symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Company's name.
    #[serde(rename = "recipientName", skip_serializing_if = "Option::is_none")]
    pub recipient_name: Option<String>,
    /// Company's name.
    #[serde(
        rename = "recipientParentName",
        skip_serializing_if = "Option::is_none"
    )]
    pub recipient_parent_name: Option<String>,
    /// Description.
    #[serde(rename = "awardDescription", skip_serializing_if = "Option::is_none")]
    pub award_description: Option<String>,
    /// Recipient's country.
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// Period.
    #[serde(rename = "actionDate", skip_serializing_if = "Option::is_none")]
    pub action_date: Option<String>,
    /// Income reported by lobbying firms.
    #[serde(rename = "totalValue", skip_serializing_if = "Option::is_none")]
    pub total_value: Option<f32>,
    /// Performance start date.
    #[serde(
        rename = "performanceStartDate",
        skip_serializing_if = "Option::is_none"
    )]
    pub performance_start_date: Option<String>,
    /// Performance end date.
    #[serde(rename = "performanceEndDate", skip_serializing_if = "Option::is_none")]
    pub performance_end_date: Option<String>,
    /// Award agency.
    #[serde(rename = "awardingAgencyName", skip_serializing_if = "Option::is_none")]
    pub awarding_agency_name: Option<String>,
    /// Award sub-agency.
    #[serde(
        rename = "awardingSubAgencyName",
        skip_serializing_if = "Option::is_none"
    )]
    pub awarding_sub_agency_name: Option<String>,
    /// Award office name.
    #[serde(rename = "awardingOfficeName", skip_serializing_if = "Option::is_none")]
    pub awarding_office_name: Option<String>,
    /// Performance country.
    #[serde(rename = "performanceCountry", skip_serializing_if = "Option::is_none")]
    pub performance_country: Option<String>,
    /// Performance city.
    #[serde(rename = "performanceCity", skip_serializing_if = "Option::is_none")]
    pub performance_city: Option<String>,
    /// Performance county.
    #[serde(rename = "performanceCounty", skip_serializing_if = "Option::is_none")]
    pub performance_county: Option<String>,
    /// Performance state.
    #[serde(rename = "performanceState", skip_serializing_if = "Option::is_none")]
    pub performance_state: Option<String>,
    /// Performance zip code.
    #[serde(rename = "performanceZipCode", skip_serializing_if = "Option::is_none")]
    pub performance_zip_code: Option<String>,
    /// Performance congressional district.
    #[serde(
        rename = "performanceCongressionalDistrict",
        skip_serializing_if = "Option::is_none"
    )]
    pub performance_congressional_district: Option<String>,
    /// NAICS code.
    #[serde(rename = "naicsCode", skip_serializing_if = "Option::is_none")]
    pub naics_code: Option<String>,
    /// Permalink.
    #[serde(rename = "permalink", skip_serializing_if = "Option::is_none")]
    pub permalink: Option<String>,
}

impl UsaSpending {
    pub fn new() -> UsaSpending {
        UsaSpending {
            symbol: None,
            recipient_name: None,
            recipient_parent_name: None,
            award_description: None,
            country: None,
            action_date: None,
            total_value: None,
            performance_start_date: None,
            performance_end_date: None,
            awarding_agency_name: None,
            awarding_sub_agency_name: None,
            awarding_office_name: None,
            performance_country: None,
            performance_city: None,
            performance_county: None,
            performance_state: None,
            performance_zip_code: None,
            performance_congressional_district: None,
            naics_code: None,
            permalink: None,
        }
    }
}
