/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsptoPatent {
    /// Application Number.
    #[serde(rename = "applicationNumber", skip_serializing_if = "Option::is_none")]
    pub application_number: Option<String>,
    /// Array of companies' name on the patent.
    #[serde(rename = "companyFilingName", skip_serializing_if = "Option::is_none")]
    pub company_filing_name: Option<Vec<String>>,
    /// Filing date.
    #[serde(rename = "filingDate", skip_serializing_if = "Option::is_none")]
    pub filing_date: Option<String>,
    /// Description.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Filing status.
    #[serde(rename = "filingStatus", skip_serializing_if = "Option::is_none")]
    pub filing_status: Option<String>,
    /// Patent number.
    #[serde(rename = "patentNumber", skip_serializing_if = "Option::is_none")]
    pub patent_number: Option<String>,
    /// Publication date.
    #[serde(rename = "publicationDate", skip_serializing_if = "Option::is_none")]
    pub publication_date: Option<String>,
    /// Patent's type.
    #[serde(rename = "patentType", skip_serializing_if = "Option::is_none")]
    pub patent_type: Option<String>,
    /// URL of the original article.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl UsptoPatent {
    pub fn new() -> UsptoPatent {
        UsptoPatent {
            application_number: None,
            company_filing_name: None,
            filing_date: None,
            description: None,
            filing_status: None,
            patent_number: None,
            publication_date: None,
            patent_type: None,
            url: None,
        }
    }
}
