/*
 * Finnhub API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VisaApplication {
    /// Year.
    #[serde(rename = "year", skip_serializing_if = "Option::is_none")]
    pub year: Option<i64>,
    /// Quarter.
    #[serde(rename = "quarter", skip_serializing_if = "Option::is_none")]
    pub quarter: Option<i64>,
    /// Symbol.
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Case number.
    #[serde(rename = "caseNumber", skip_serializing_if = "Option::is_none")]
    pub case_number: Option<String>,
    /// Case status.
    #[serde(rename = "caseStatus", skip_serializing_if = "Option::is_none")]
    pub case_status: Option<String>,
    /// Received date.
    #[serde(rename = "receivedDate", skip_serializing_if = "Option::is_none")]
    pub received_date: Option<String>,
    /// Visa class.
    #[serde(rename = "visaClass", skip_serializing_if = "Option::is_none")]
    pub visa_class: Option<String>,
    /// Job Title.
    #[serde(rename = "jobTitle", skip_serializing_if = "Option::is_none")]
    pub job_title: Option<String>,
    /// SOC Code. A list of SOC code can be found <a href=\"https://www.bls.gov/oes/current/oes_stru.htm\" target=\"_blank\">here</a>.
    #[serde(rename = "socCode", skip_serializing_if = "Option::is_none")]
    pub soc_code: Option<String>,
    /// Full-time position flag.
    #[serde(rename = "fullTimePosition", skip_serializing_if = "Option::is_none")]
    pub full_time_position: Option<String>,
    /// Job's start date.
    #[serde(rename = "beginDate", skip_serializing_if = "Option::is_none")]
    pub begin_date: Option<String>,
    /// Job's end date.
    #[serde(rename = "endDate", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    /// Company's name.
    #[serde(rename = "employerName", skip_serializing_if = "Option::is_none")]
    pub employer_name: Option<String>,
    /// Worksite address.
    #[serde(rename = "worksiteAddress", skip_serializing_if = "Option::is_none")]
    pub worksite_address: Option<String>,
    /// Worksite city.
    #[serde(rename = "worksiteCity", skip_serializing_if = "Option::is_none")]
    pub worksite_city: Option<String>,
    /// Worksite county.
    #[serde(rename = "worksiteCounty", skip_serializing_if = "Option::is_none")]
    pub worksite_county: Option<String>,
    /// Worksite state.
    #[serde(rename = "worksiteState", skip_serializing_if = "Option::is_none")]
    pub worksite_state: Option<String>,
    /// Worksite postal code.
    #[serde(rename = "worksitePostalCode", skip_serializing_if = "Option::is_none")]
    pub worksite_postal_code: Option<String>,
    /// Wage range from.
    #[serde(rename = "wageRangeFrom", skip_serializing_if = "Option::is_none")]
    pub wage_range_from: Option<f32>,
    /// Wage range to.
    #[serde(rename = "wageRangeTo", skip_serializing_if = "Option::is_none")]
    pub wage_range_to: Option<f32>,
    /// Wage unit of pay.
    #[serde(rename = "wageUnitOfPay", skip_serializing_if = "Option::is_none")]
    pub wage_unit_of_pay: Option<String>,
    /// Wage level.
    #[serde(rename = "wageLevel", skip_serializing_if = "Option::is_none")]
    pub wage_level: Option<String>,
    /// H1B dependent flag.
    #[serde(rename = "h1bDependent", skip_serializing_if = "Option::is_none")]
    pub h1b_dependent: Option<String>,
}

impl VisaApplication {
    pub fn new() -> VisaApplication {
        VisaApplication {
            year: None,
            quarter: None,
            symbol: None,
            case_number: None,
            case_status: None,
            received_date: None,
            visa_class: None,
            job_title: None,
            soc_code: None,
            full_time_position: None,
            begin_date: None,
            end_date: None,
            employer_name: None,
            worksite_address: None,
            worksite_city: None,
            worksite_county: None,
            worksite_state: None,
            worksite_postal_code: None,
            wage_range_from: None,
            wage_range_to: None,
            wage_unit_of_pay: None,
            wage_level: None,
            h1b_dependent: None,
        }
    }
}
